INSERT INTO "dim_province"
VALUES
('01', 'Ha Noi', 'Red River Delta'),
('02', 'Ho Chi Minh City', 'Southeast'),
('03', 'Hai Phong', 'Red River Delta'),
('04', 'Da Nang', 'South Central'),
('05', 'Ha Giang', 'Northeast'),
('06', 'Cao  Bang', 'Northeast'),
('07', 'Lai Chau', 'Northwest'),
('08', 'Lao Cai', 'Northwest'),
('09', 'Tuyen Quang', 'Northeast'),
('10', 'Lang Son', 'Northeast'),
('11', 'Bac Kan', 'Northeast'),
('12', 'Thai Nguyen', 'Northeast'),
('13', 'Yen Bai', 'Northwest'),
('14', 'Son La', 'Northwest'),
('15', 'Phu Tho', 'Northeast'),
('16', 'Vinh Phuc', 'Red River Delta'),
('17', 'Quang Ninh', 'Northeast'),
('18', 'Bac Giang', 'Northeast'),
('19', 'Bac Ninh', 'Red River Delta'),
('21', 'Hai Duong', 'Red River Delta'),
('22', 'Hung Yen', 'Red River Delta'),
('23', 'Hoa Binh', 'Northwest'),
('24', 'Ha Nam', 'Red River Delta'),
('25', 'Nam Dinh', 'Red River Delta'),
('26', 'Thai Binh', 'Red River Delta'),
('27', 'Ninh Binh', 'Red River Delta'),
('28', 'Thanh Hoa', 'North Central'),
('29', 'Nghe An', 'North Central'),
('30', 'Ha Tinh', 'North Central'),
('31', 'Quang Binh', 'North Central'),
('32', 'Quang Tri', 'North Central'),
('33', 'Thua Thien-Hue', 'North Central'),
('34', 'Quang Nam', 'South Central'),
('35', 'Quang Ngai', 'South Central'),
('36', 'Kon Tum', 'Central Highlands'),
('37', 'Binh Dinh', 'South Central'),
('38', 'Gia Lai', 'Central Highlands'),
('39', 'Phu Yen', 'South Central'),
('40', 'Dak Lak', 'Central Highlands'),
('41', 'Khanh Hoa', 'South Central'),
('42', 'Lam Dong', 'Central Highlands'),
('43', 'Binh Phuoc', 'Southeast'),
('44', 'Binh Duong', 'Southeast'),
('45', 'Ninh Thuan', 'South Central'),
('46', 'Tay Ninh', 'Southeast'),
('47', 'Binh Thuan', 'South Central'),
('48', 'Dong Nai', 'Southeast'),
('49', 'Long An', 'Mekong River Delta'),
('50', 'Dong Thap', 'Mekong River Delta'),
('51', 'An Giang', 'Mekong River Delta'),
('52', 'Ba ria-Vung Tau', 'Southeast'),
('53', 'Tien Giang', 'Mekong River Delta'),
('54', 'Kien Giang', 'Mekong River Delta'),
('55', 'Can Tho', 'Mekong River Delta'),
('56', 'Ben Tre', 'Mekong River Delta'),
('57', 'Vinh Long', 'Mekong River Delta'),
('58', 'Tra Vinh', 'Mekong River Delta'),
('59', 'Soc Trang', 'Mekong River Delta'),
('60', 'Bac Lieu', 'Mekong River Delta'),
('61', 'Ca Mau', 'Mekong River Delta'),
('62', 'Dien Bien', 'Northwest'),
('63', 'Dak Nong', 'Central Highlands'),
('64', 'Hau Giang', 'Mekong River Delta')
