-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.dim_date
(
    year integer NOT NULL,
    day integer NOT NULL,
    month integer NOT NULL,
    CONSTRAINT dim_date_pkey PRIMARY KEY (year)
);

CREATE TABLE IF NOT EXISTS public.dim_province
(
    "province_id" text NOT NULL,
    province_name text COLLATE pg_catalog."default" NOT NULL,
    area text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT dim_province_pkey PRIMARY KEY ("province_id")
);

CREATE TABLE IF NOT EXISTS public.fact_score
(
    "row_id" bigint NOT NULL,
    year integer NOT NULL,
    "province_id" text NOT NULL,
    "student_id" text COLLATE pg_catalog."default" NOT NULL,
    mathematics_score double precision,
    literature_score double precision,
    foreign_language_score double precision,
    foreign_language_code text COLLATE pg_catalog."default",
    physics_score double precision,
    chemistry_score double precision,
    biology_score double precision,
    history_score double precision,
    geography_score double precision,
    civic_education_score double precision,
    CONSTRAINT fact_score_pkey PRIMARY KEY ("row_id")
);

ALTER TABLE IF EXISTS public.fact_score
    ADD CONSTRAINT "fact_score_province_id_fkey" FOREIGN KEY ("province_id")
    REFERENCES public.dim_province ("province_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.fact_score
    ADD CONSTRAINT fact_score_year_fkey FOREIGN KEY (year)
    REFERENCES public.dim_date (year) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;